// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.secrets@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = false;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const SECRETS_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const SECRETS_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_secrets { () => { "{\"capability_id\":\"lenso.secrets@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"resolve\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_secrets_client { () => { "{\"capability_id\":\"lenso.secrets@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_secrets_client { () => { "{\"capability_id\":\"lenso.secrets@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const RESOLVE_OPERATION: &str = "resolve";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ResolveRequest {
    #[serde(rename = "reference")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reference: String,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ResolveResponse {
    #[serde(rename = "value")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub value: String,
}

impl fmt::Debug for ResolveResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ResolveResponse")
            .field("value", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum ResolveError {
    InvalidReference,
    UnknownReference,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct Secrets;
impl RequestCapability for Secrets {
    type Request = ResolveRequest;
    type Response = ResolveResponse;
    type DomainError = ResolveError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != RESOLVE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<SecretsRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).resolve(context, request)
    }
}

impl serde::Serialize for ResolveError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidReference => serializer.serialize_str("invalid_reference"),
            Self::UnknownReference => serializer.serialize_str("unknown_reference"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ResolveError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_reference" => Ok(Self::InvalidReference),
                "unknown_reference" => Ok(Self::UnknownReference),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_resolve_request(value: &ResolveRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_resolve_request(wire: &str) -> Result<ResolveRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_resolve_response(value: &ResolveResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_resolve_response(wire: &str) -> Result<ResolveResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_resolve_error(value: &ResolveError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_resolve_error(wire: &str) -> Result<ResolveError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoSecretsResolveResult {
    fn __lenso_into_result(self) -> Result<Result<ResolveResponse, ResolveError>, RuntimeFailure>;
}
impl __LensoIntoSecretsResolveResult for Result<ResolveResponse, ResolveError> {
    fn __lenso_into_result(self) -> Result<Result<ResolveResponse, ResolveError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoSecretsResolveResult for Result<Result<ResolveResponse, ResolveError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ResolveResponse, ResolveError>, RuntimeFailure> { self }
}
impl __LensoIntoSecretsResolveResult for Result<ResolveResponse, lenso_plugin_authoring::PluginError<ResolveError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ResolveResponse, ResolveError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoSecretsResolveResult for Result<ResolveResponse, SecretsInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ResolveResponse, ResolveError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(SecretsInvocationError::Domain(error)) => Ok(Err(error)),
            Err(SecretsInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait SecretsProvider: fmt::Debug + 'static {
    fn resolve(&self, context: InvocationContext, request: ResolveRequest) -> NativeRequestFuture<Secrets>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_secrets {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportSecrets;
        impl $crate::SecretsProvider for $plugin {
        fn resolve(&self, context: __LensoNativeSupportSecrets::InvocationContext, request: $crate::ResolveRequest) -> __LensoNativeSupportSecrets::NativeRequestFuture<$crate::Secrets> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::resolve(&plugin, context, request).await;
                $crate::__LensoIntoSecretsResolveResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct SecretsRequestEndpoint { provider: Rc<dyn SecretsProvider> }

#[derive(Debug)]
pub struct SecretsEndpoint<P: SecretsProvider> { provider: Rc<P>, request_endpoint: SecretsRequestEndpoint }
impl<P: SecretsProvider> SecretsEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn SecretsProvider> = provider.clone();
        Self { provider, request_endpoint: SecretsRequestEndpoint { provider: request_provider } }
    }
}

impl<P: SecretsProvider> NativeRequestEndpoint for SecretsEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        RESOLVE_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            RESOLVE_OPERATION => {
                let Ok(request) = request.downcast::<ResolveRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).resolve(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_secrets {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::SecretsEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_secrets {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_secrets!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct SecretsClient {
    resolve: NativeRequestHandle<Secrets>,
}
impl SecretsClient {
    pub fn new(handle: NativeRequestHandle<Secrets>) -> Self {
        Self { resolve: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn resolve(&self, request: ResolveRequest) -> Result<ResolveResponse, SecretsInvocationError> {
        self.resolve.invoke(RESOLVE_OPERATION, request).await
            .map_err(SecretsInvocationError::Runtime)?
            .map_err(SecretsInvocationError::Domain)
    }

    pub async fn resolve_with_context(&self, context: InvocationContext, request: ResolveRequest) -> Result<ResolveResponse, SecretsInvocationError> {
        self.resolve.invoke_with_context(RESOLVE_OPERATION, context, request).await
            .map_err(SecretsInvocationError::Runtime)?
            .map_err(SecretsInvocationError::Domain)
    }
}

impl CapabilityClient for SecretsClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            resolve: dependencies.one::<Secrets>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for SecretsClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    resolve: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<Secrets>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum SecretsInvocationError {
    Domain(ResolveError),
    Runtime(RuntimeFailure),
}
